# Generated by Django 3.2.6 on 2021-08-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_age', models.PositiveIntegerField()),
                ('doctor_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('e', 'Does not want to mention')], max_length=10)),
                ('doctor_designation', models.CharField(max_length=50)),
                ('doctor_phone_number', models.CharField(max_length=12)),
                ('doctor_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('e', 'Does not want to mention')], max_length=10)),
                ('patient_bloodgroup', models.CharField(max_length=6)),
                ('patient_phone_number', models.CharField(max_length=12)),
                ('patient_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='record_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allergic', models.BooleanField()),
                ('patient_description_file', models.TextField()),
                ('date_of_attendance', models.DateField()),
                ('time_of_attendance', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients_record.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_record.patientprofile')),
            ],
        ),
    ]
